drop table BASISPREIS;
drop table FILM;
drop table GENRE;
drop table GÜLTIGKEITSBEREICH;
drop table KARTE;
drop table KINO;
drop table KUNDENGRUPPE;
drop table LOKALITÄT;
drop table MODIFIKATION_BENUTZUNG;
drop table PREISLISTE;
drop table PREISMODIFIKATION;
drop table PREIS_ANWENDUNG;
drop table RANG;
drop table RANG_PREIS;
drop table REIHE;
drop table SITZPLATZ;
drop table SPIELPLAN;
drop table VORFÜHRSAAL;
drop table VORFÜHRUNG;
drop table WOCHENTAG;
drop table ZEITPLAN;
drop table ZEITSLOT;

COMMIT;